[package]
name = "plop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.*", features = ["full"] }
actix-web = { version = "4", features = ["rustls"] }
rustls = "0.21.*"