//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "video_upload_state")]
pub enum VideoUploadState {
    #[sea_orm(string_value = "available")]
    Available,
    #[sea_orm(string_value = "unavailable")]
    Unavailable,
    #[sea_orm(string_value = "uploading")]
    Uploading,
}
