//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::VideoUploadState;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "video")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub user_id: String,
    pub title: String,
    pub description: Option<String>,
    pub tags: Option<String>,
    pub timestamp: DateTime,
    pub views: i64,
    pub likes: i64,
    #[sea_orm(column_type = "Double")]
    pub duration: f64,
    pub framerate: i16,
    pub has_audio: bool,
    pub state_144p: VideoUploadState,
    pub state_240p: VideoUploadState,
    pub state_360p: VideoUploadState,
    pub state_480p: VideoUploadState,
    pub state_720p: VideoUploadState,
    pub state_1080p: VideoUploadState,
    pub state_1440p: VideoUploadState,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
